from selenium.webdriver.common.by import By

button_order_large = [By.XPATH, "//div[5]/button[text()='Заказать']"]
button_order_medium = [By.XPATH, "//div[3]/button[2][text()='Заказать']"]
button_order_small = [By.XPATH, "//div[2]/button[1][text()='Заказать']"]
input_name = [By.XPATH, "//input[@placeholder='* Имя']"]
input_surname = [By.XPATH, "//input[@placeholder='* Фамилия']"]
input_address = [By.XPATH, "//input[@placeholder='* Адрес: куда привезти заказ']"]
input_metro_station = [By.XPATH, "//input[@placeholder='* Станция метро']"]
input_phone = [By.XPATH, "//input[@placeholder='* Телефон: на него позвонит курьер']"]
button_next_step = [By.XPATH, "//button[text()='Далее']"]
header_about_rent = [By.XPATH, "//div[text()='Про аренду']"]
input_rent_date = [By.XPATH, "//input[@placeholder='* Когда привезти самокат']"]
dropdown_rent_duration = [By.XPATH, "//div[text()='* Срок аренды']"]
option_one_day = [By.XPATH, "//div[text()='сутки']"]
checkbox_black_scooter = [By.XPATH, "//input[@id='black']"]
input_comment = [By.XPATH, "//input[@placeholder='Комментарий для курьера']"]
button_confirm_yes = [By.XPATH, "//button[text()='Да']"]
message_order_success = [By.XPATH, "//div[text()='Заказ оформлен']"]
logo_main_scooter = [By.XPATH, "//img[@alt='Scooter']"]
logo_yandex_main = [By.XPATH, "//img[@alt='Yandex']"]
header_scooter_main = [By.XPATH, "//div[text()='Самокат ']"]
button_search_dzen = [By.XPATH, "//button[text()='Найти']"]
button_check_status = [By.XPATH, "//button[text()='Посмотреть статус']"]
button_accept_cookies = [By.CLASS_NAME, "App_CookieButton__3cvqF"]
